methods: [1, 2, 5, 7]
Ns: [128, 256,  512, 1024]
threads: [32, 64, 128]
teams: [8, 16, 32]
job: demo_run
IDA: 27
machine: grace
methohd_tag: arraybench

generate_plots:
 overhead_distribution: true
 thread_vs_overhead: true
 team_vs_overhead: true
 n_vs_overhead: true
