# Compiler and flags for OpenACC builds.
#
# On Cray systems, `cc` selects the active programming environment.
# Outside Cray, default to NVIDIA HPC SDK's nvc.

PE_ENV ?= $(shell echo $$PE_ENV)

ifeq ($(PE_ENV),CRAY)
    CC = cc
    CFLAGS = -hacc -O0
else ifeq ($(PE_ENV),GNU)
    CC = cc
    CFLAGS = -fopenacc -O0
else ifeq ($(PE_ENV),NVHPC)
    CC = nvc
    CFLAGS = -acc -Minfo=accel -O0
else
    CC = nvc
    CFLAGS = -acc -Minfo=accel -O0
endif

LDFLAGS =
CPPFLAGS = -E -O0
LIBS = -lm
