#!/bin/bash
#SBATCH --account=d35-wt
#SBATCH --job-name=Final
#SBATCH --time=8:00:00
#SBATCH --nodes=1
#SBATCH --partition=gpu
#SBATCH --qos=gpu-exc
#SBATCH --gres=gpu:1
#SBATCH --exclusive
#SBATCH --output=MBResult/%x_%j.out

# gcc -fopenmp -fopenmp-targets=nvptx-none -### /dev/null 2>&1 | grep "Configured with"
# echo | gcc -fopenmp -dM -E - | grep _OPENMP
# module load gcc/12.3.0-offload
# export NV_ACC_CUDA_HEAPSIZE=4GB
export OMP_TARGET_OFFLOAD=mandatory
module load PrgEnv-amd
module load craype-accel-amd-gfx90a
module load craype-x86-milan
# module load intel-license
# module load intel-20.4/cc
# module load intel-20.4/fc
# module load intel-20.4/compilers 
# module load mpt
# module load nvidia/nvhpc
srun ./run.sh
